export const s = {
  wrap: { display: "flex", minHeight: "100vh", fontFamily: "sans-serif", fontSize: "14px", background: "#f3f4f6", color: "#1f2937" },
  sidebar: { width: "220px", background: "#312e81", color: "white", padding: "24px 16px", display: "flex", flexDirection: "column", justifyContent: "space-between", flexShrink: 0 },
  logo: { fontSize: "20px", fontWeight: "900", marginBottom: "32px", letterSpacing: "2px" },
  navBtn: (active) => ({ display: "block", width: "100%", textAlign: "left", padding: "10px 12px", borderRadius: "6px", border: "none", cursor: "pointer", fontSize: "13px", fontWeight: "500", marginBottom: "4px", background: active ? "#4338ca" : "transparent", color: "white" }),
  main: { flex: 1, padding: "32px", overflowY: "auto" },
  h1: { fontSize: "26px", fontWeight: "900", marginBottom: "6px" },
  sub: { color: "#6b7280", marginBottom: "28px" },
  grid3: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "16px", marginBottom: "28px" },
  card: { background: "white", padding: "20px", borderRadius: "12px", border: "1px solid #e5e7eb" },
  cardLabel: { fontSize: "11px", fontWeight: "700", color: "#9ca3af", textTransform: "uppercase", marginBottom: "6px" },
  statNum: (color) => ({ fontSize: "28px", fontWeight: "900", color }),
  chartBox: { background: "white", padding: "20px", borderRadius: "12px", border: "1px solid #e5e7eb", marginBottom: "28px" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 2fr", gap: "24px" },
  formBox: { background: "white", padding: "20px", borderRadius: "12px", border: "1px solid #e5e7eb" },
  label: { display: "block", fontSize: "13px", fontWeight: "700", marginBottom: "4px" },
  input: { width: "100%", border: "1px solid #d1d5db", borderRadius: "6px", padding: "8px", fontSize: "13px", boxSizing: "border-box", marginBottom: "12px" },
  select: { width: "100%", border: "1px solid #d1d5db", borderRadius: "6px", padding: "8px", fontSize: "13px", boxSizing: "border-box", marginBottom: "12px", background: "white" },
  btn: (color) => ({ width: "100%", background: color, color: "white", border: "none", borderRadius: "6px", padding: "10px", fontWeight: "700", fontSize: "13px", cursor: "pointer" }),
  tableWrap: { background: "white", padding: "20px", borderRadius: "12px", border: "1px solid #e5e7eb" },
  th: { padding: "10px 12px", textAlign: "left", background: "#f9fafb", fontSize: "12px", fontWeight: "700", borderBottom: "1px solid #e5e7eb" },
  td: { padding: "10px 12px", borderBottom: "1px solid #f3f4f6", fontSize: "13px" },
  badge: { padding: "2px 8px", borderRadius: "20px", fontSize: "11px", fontWeight: "700", background: "#fef3c7", color: "#92400e" },
  grid2eq: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "24px" },
  profileBox: { background: "white", padding: "24px", borderRadius: "12px", border: "1px solid #e5e7eb", maxWidth: "400px" },
  footerText: { fontSize: "11px", opacity: "0.7" },
};
